### PR TITLE
Remove Kotlin Types from API

### PR DESCRIPTION
**Pull request by stevensJourney**
# Overview

This PR removes all Kotlin types from public-facing APIs and introduces numerous quality-of-life improvements to the Swift SDK.

Removing Kotlin interfaces removes coupling between the Swift and Kotlin SDKs. This removes some weird behaviour where users have to interface with translated Kotlin code. Declaring protocols in the Swift SDK also allows for generating better documentation with SwiftDoc comments.

## Explicit Swift Interfaces

Previously, Kotlin interfaces/types were used for:

- Sync Status  
- Transaction Contexts  
- CRUD batches, transactions, and entries  
- SQL Cursor  
- JSON parameters for client parameters  

Some of these Kotlin interfaces made the Swift SDK unpleasant to use. These have now been replaced with Swift protocols, along with quality-of-life improvements using native Swift types where applicable. Adapters link the Kotlin implementation to these Swift protocols.

### ✅ Sync Status

The Kotlin `SyncStatus` interface was previously exposed directly through the `PowerSyncDatabase`'s `currentStatus` field, requiring users to interface with SKIEE-translated Kotlin types.

For example, `lastSyncedAt` was represented as a Kotlin Date:

```swift
/// This is clunky and requires overhead for optional handling.
/// `lastSyncedAt` is of type PSKKotlinx_datetimeInstant
let time: Date = Date(
    timeIntervalSince1970: TimeInterval(database.currentStatus.lastSyncedAt!.epochSeconds)
)
```

This has been replaced with a native Swift interface. Users now receive Swift-native values like `Date` directly.

### ✅ Transaction Contexts

SKIEE translates generic Kotlin functions to return `Any`, which leads to the loss of generics and requires unsafe casting.

**Before:**

```swift
let attachmentIDs = try transaction.getAll(
    sql: "SELECT photo_id FROM \(TODOS_TABLE) WHERE list_id = ? AND photo_id IS NOT NULL",
    parameters: [id]
) { cursor in
    cursor.getString(index: 0)! // Force unwrap — not ideal
} as? [String] // Manual cast required
```

**After:**

```swift
let attachmentIDs = try transaction.getAll(
    sql: "SELECT photo_id FROM \(TODOS_TABLE) WHERE list_id = ? AND photo_id IS NOT NULL",
    parameters: [id]
) { cursor in
    try cursor.getString(index: 0)
} // Swift infers attachmentIDs as [String]
```

**Bonus:**  
`execute` methods return an `Int64` (affected rows), but for PowerSync, this is usually ignored due to use of views. The return value is now marked `@discardableResult` to silence warnings:

```swift
try await database.execute(
    sql: "INSERT INTO users (id, name, email) VALUES (?, ?, ?)",
    parameters: ["1", "Test User", "test@example.com"]
)
```

**Extra Bonus:**  
SQL parameter arrays now support `nil` values via `[Any?]` instead of `[Any]`, resolving compiler warnings:

Compiler warning screenshot

### ✅ CRUD Operations

CRUD operations like `getNextCrudTransaction` and `getCrudBatch` previously returned Kotlin containers.

**Before:**

```swift
_ = try await transaction.complete.invoke(p1: nil)
```

**After:**

```swift
try await transaction.complete()
```

The Swift interface is clearer and supports the optional `writeCheckpoint` parameter directly.

### ✅ SQL Cursors

Cursor APIs previously returned Kotlin primitive wrappers, requiring manual unwrapping:

**Before:**

```swift
let users: [(String, String)] = try await database.getAll(
    sql: "SELECT id, name FROM users WHERE password = ? ORDER BY id",
    parameters: [nil]
) { cursor in
    try (
        cursor.getBoolean(index: 0)?.boolValue, // Kotlin Bool
        cursor.getDouble(index: 1)?.value,      // Kotlin Double
        cursor.getLong(index: 2)?.int64Value    // Kotlin Long
    )
}
```

**Improvements:**

- New `getInt` and `getInt64` methods for size-specific integer access
- Better consistency between index and name-based getters

**Breaking change:**  
Index-based getters now match the behavior of named column getters:

A `SqlCursorError` Error type is introduced which handles error cases e.g. when required column values are `nil` valued or if a column name is not present in the query result set. These exceptions will propagate from the `mapper` to the top-level query method (e.g `get`)

```swift
try cursor.getBoolean(index: 0) // Non-optional Swift Bool, throws if nil
cursor.getBooleanOptional(index: 0) // Optional Swift Bool
```

---

### ✅ JSON Client Parameters

The `connect` method previously accepted `[String: Any]`, which caused runtime crashes due to SKIEE requiring Kotlin `JSONParam` values.

**Before (crashes at runtime):**

```swift
try await database.connect(
    connector: PowerSyncBackendConnector(),
    params: [
        "foo": "bar"
    ]
)
```

**After (strongly typed Swift API):**

```swift
try await database.connect(
    connector: PowerSyncBackendConnector(),
    params: [
        "foo": .string("bar")
    ]
)
```

New Swift-native `JsonParam` and `JsonValue` enums prevent type mismatches and runtime crashes.

## TODOS

- [ ] This requires https://github.com/powersync-ja/powersync-kotlin/pull/182/files. Tests pass locally if linked. 
      - [ ] The Kotlin KMM bridge deploy process requires some work in order to publish v1.0.0 of the KMM artifact.

### CODE REVIEW

File: Sources/PowerSync/QueriesProtocol.swift [hunk 1]
```diff
@@ -20,67 +24,37 @@ public struct WatchOptions<RowType> {
 public protocol Queries {
     /// Execute a write query (INSERT, UPDATE, DELETE)
     /// Using `RETURNING *` will result in an error.
-    func execute(sql: String, parameters: [Any]?) async throws -> Int64
-
-    /// Execute a read-only (SELECT) query and return a single result.
-    /// If there is no result, throws an IllegalArgumentException.
-    /// See `getOptional` for queries where the result might be empty.
-    func get<RowType>(
```
Comment (stevensJourney) [inline Sources/PowerSync/QueriesProtocol.swift:28]: Previously we had multiple definitions of the `get` method. A definition was included for versions where the `mapper` could `throw` or not. Throwing functions are a superset of non-throwing functions in Swift. A single declaration where `mapper` can throw allows passing a mapper which does not throw. I've removed these duplicates.

File: Sources/PowerSync/Kotlin/DatabaseLogger.swift [hunk 2]
```diff
@@ -44,7 +44,7 @@ private class KermitLogWriterAdapter: Kermit_coreLogWriter {
 ///
 /// This class bridges Swift log writers with the Kotlin logging system and supports
 /// runtime configuration of severity levels and writer lists.
-internal class DatabaseLogger: LoggerProtocol {
+class DatabaseLogger: LoggerProtocol {
```
[the remark this answers is not in the document]
Comment (simolus3) [reply Sources/PowerSync/Kotlin/DatabaseLogger.swift:47]: Yeah it looks like `internal` is the default.

**Review by simolus3 — COMMENTED** [review]
I think it's fantastic that we have a proper Swift API now, so the changes look good to me.

One thing that I think we should consider before we need to avoid breaking changes altogether: It looks like using a double representing seconds is the canonical way to represent durations in Swift, so maybe adopting that for our APIs that currently accept millis (and then normalizing to millis for Kotlin) may be a change worth making. But that's also pretty minor, so perhaps not worth it.

Also: `PowerSyncBackendConnectorAdapter.swift` was moved into `kotlin` (lowercase), the other files are in `Kotlin` (uppercase).

File: Sources/PowerSync/Kotlin/db/KotlinSqlCursor.swift [hunk 3]
```diff
@@ -0,0 +1,144 @@
...
+        guard let result = try getBooleanOptional(name: name) else {
+            throw SqlCursorError.nullValueFound(name)
+        }
+        return result
+    }
+    
+    func getBooleanOptional(name: String) throws -> Bool? {
+        try guardColumnName(name)
+        return try base.getBooleanOptional(name: name)?.boolValue
+    }
```
[the remark this answers is not in the document]
Comment (stevensJourney) [reply Sources/PowerSync/Kotlin/db/KotlinSqlCursor.swift]: That is a good suggestion. I've shared the implementation in the named optional getters. The required getters, e.g. `getBoolean(name: String)` are trickier to make this suggested change. The reason being that those methods throw a `nullValueFound` Error which should relate to the column name specified. If I used the indexed based version then column name would be replaced with the index.

File: Sources/PowerSync/Protocol/PowerSyncDatabaseProtocol.swift [hunk 4]
```diff
@@ -1,5 +1,52 @@
...
 
+/// Options for configuring a PowerSync connection.
+///
+/// Provides optional parameters to customize sync behavior such as throttling and retry policies.
+public struct ConnectOptions {
+    /// Time in milliseconds between CRUD (Create, Read, Update, Delete) operations.
+    ///
+    /// Default is `1000` ms (1 second).
+    /// Increase this value to reduce load on the backend server.
+    public var crudThrottleMs: Int64
```
[the remark this answers is not in the document]
Comment (stevensJourney) [reply Sources/PowerSync/Protocol/PowerSyncDatabaseProtocol.swift]: This is a fair recommendation. I think it's worthwhile to make this change. I've updated the `crudThrottleMs`, `retryDelayMs` and `throttleMs` params to TimeInterval. The changelog has been updated to include notes about the breaking changes.
